# Generated by Django 3.0 on 2021-01-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('review_count', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Positive', 'positive'), ('Negative', 'negative'), ('Neutral', 'neutral')], max_length=10)),
                ('price', models.IntegerField()),
                ('display_phone', models.CharField(max_length=20)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=10)),
                ('address', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'ordering': ('-score',),
            },
        ),
    ]
