# Generated by Django 3.0 on 2021-01-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ('night_price',)},
        ),
    ]
