# Generated by Django 3.1.4 on 2021-01-03 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rental_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('food_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gym_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transportation_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fav_rental_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
